# Generated by Django 3.0.6 on 2020-05-09 01:14

from django.db import migrations, models
import index.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, validators=[index.helpers.validators.validate_phone]),
        ),
    ]
