# Generated by Django 3.0.6 on 2020-05-10 01:52

from django.db import migrations, models
import index.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200509_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, validators=[index.helpers.validators.validate_phone]),
        ),
    ]
