# Generated by Django 3.0.6 on 2020-05-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200509_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/profiles/profile.jpg', null=True, upload_to='media/profiles'),
        ),
    ]
