# Generated by Django 3.0.4 on 2020-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200511_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/default/no_photo.png', null=True, upload_to='media/profiles'),
        ),
    ]
