
version: '3.1'

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: digimenu
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: digimenu
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    secrets:
      - db_password

  digimenu:
    build: .
    image: prod/digimenu
    container_name: digimenu
    environment:
      DJANGO_SUPERUSER_NAME: digimenuadmin
      DJANGO_SUPERUSER_MAIL: /run/secrets/django_superuser_mail
      DJANGO_SUPERUSER_PASSWORD: /run/secrets/django_superuser_password
      ALLOWED_HOST: localhost
      DB_NAME: digimenu
      DB_USER: digimenu
      DB_PASSWORD: /run/secrets/db_password
      DB_HOST: postgres
      SECRET_KEY: /run/secrets/secret_key
      EMAIL_HOST_USER: /run/secrets/email_host_user
      EMAIL_HOST_PASSWORD: /run/secrets/email_host_password
      AWS_ACCESS_KEY_ID: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws_secret_access_key
      AWS_STORAGE_BUCKET_NAME: /run/secrets/aws_storage_bucket_name
    secrets:
      - django_superuser_mail
      - django_superuser_password
      - db_password
      - secret_key
      - email_host_user
      - email_host_password
      - aws_access_key_id
      - aws_secret_access_key
      - aws_storage_bucket_name
    volumes:
      - digimenu-media-files:/opt/digimenu/media/
      - digimenu-static-files:/opt/digimenu/static/


  nginx:
    image: nginx:1.17.8-alpine
    links:
      - digimenu
    container_name: nginx_digimenu
    depends_on:
      - digimenu
    ports:
      - 80:80
      - 443:443
    volumes:
      - digimenu-media-files:/opt/digimenu/media/
      - digimenu-static-files:/opt/digimenu/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

secrets:
  django_superuser_mail:
    file: secrets/django_superuser_mail.txt
  django_superuser_password:
    file: secrets/django_superuser_password.txt
  db_password:
    file: secrets/db_password.txt
  secret_key:
    file: secrets/secret_key.txt
  email_host_user:
    file: secrets/email_host_user.txt
  email_host_password:
    file: secrets/email_host_password.txt
  aws_access_key_id:
    file: secrets/aws_access_key_id.txt
  aws_secret_access_key:
    file: secrets/aws_secret_access_key.txt
  aws_storage_bucket_name:
    file: secrets/aws_storage_bucket_name.txt


volumes:
  postgres-vol:
  digimenu-static-files:
  digimenu-media-files:
