
version: '3.1'

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: myshop
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: myshop
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    secrets:
      - db_password

  myshop:
    build: .
    image: prod/myshop
    container_name: myshop
    environment:
      DJANGO_SUPERUSER_NAME: myshopadmin
      DJANGO_SUPERUSER_MAIL: /run/secrets/django_superuser_mail
      DJANGO_SUPERUSER_PASSWORD: /run/secrets/django_superuser_password
      ALLOWED_HOST: localhost
      DB_NAME: myshop
      DB_USER: myshop
      DB_PASSWORD: /run/secrets/db_password
      DB_HOST: postgres
      SECRET_KEY: /run/secrets/secret_key
      EMAIL_HOST_USER: /run/secrets/email_host_user
      EMAIL_HOST_PASSWORD: /run/secrets/email_host_password
    secrets:
      - django_superuser_mail
      - django_superuser_password
      - db_password
      - secret_key
      - email_host_user
      - email_host_password
    volumes:
      - myshop-media-files:/opt/myshop/media/
      - myshop-static-files:/opt/myshop/static/


  nginx:
    image: nginx:1.17.8-alpine
    links:
      - myshop
    container_name: nginx_myshop
    depends_on:
      - myshop
    ports:
      - 80:80
      - 443:443
    volumes:
      - myshop-media-files:/opt/myshop/media/
      - myshop-static-files:/opt/myshop/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

secrets:
  django_superuser_mail:
    file: secrets/django_superuser_mail.txt
  django_superuser_password:
    file: secrets/django_superuser_password.txt
  db_password:
    file: secrets/db_password.txt
  secret_key:
    file: secrets/secret_key.txt
  email_host_user:
    file: secrets/email_host_user.txt
  email_host_password:
    file: secrets/email_host_password.txt


volumes:
  postgres-vol:
  myshop-static-files:
  myshop-media-files:
