# Generated by Django 3.0.6 on 2020-05-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_str',
            field=models.CharField(default='$', max_length=10, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='price_num'),
        ),
    ]
