# Generated by Django 3.0.6 on 2020-05-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20200509_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menus.Menu', verbose_name='menu'),
        ),
    ]
