# Generated by Django 3.0.6 on 2020-05-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20200510_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('', ''), ('Small', 'Small'), ('Extra small', 'Extra small'), ('medium', 'medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='', max_length=20),
        ),
    ]
