# Generated by Django 3.0.4 on 2020-05-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_auto_20200521_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
