# Generated by Django 3.0.4 on 2020-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0018_auto_20200522_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='images/default/no_photo.png', upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='logo',
            field=models.ImageField(default='images/default/no_photo.png', upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details3.html', 'large')], default='U', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('U', 'Only'), ('XS', 'Extra small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large'), ('Meal', 'Meal')], default='U', max_length=20),
        ),
    ]
