# Generated by Django 3.0.4 on 2020-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0020_auto_20200528_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_slug',
            field=models.SlugField(unique=True),
        ),
    ]
