# Generated by Django 3.0.4 on 2020-05-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0022_auto_20200530_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addson',
            name='product',
        ),
        migrations.AddField(
            model_name='productincart',
            name='add_ons',
            field=models.ManyToManyField(to='menus.AddsOn'),
        ),
    ]
