# Generated by Django 3.0.4 on 2020-05-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0023_auto_20200530_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='addson',
            name='product',
            field=models.ManyToManyField(related_name='adds_ons', to='menus.Item'),
        ),
    ]
