# Generated by Django 3.0.4 on 2020-05-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0025_auto_20200530_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addson',
            name='product',
            field=models.ManyToManyField(related_name='adds_ons', to='menus.Price'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
