# Generated by Django 3.0.4 on 2020-05-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0026_auto_20200530_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
