# Generated by Django 3.0.4 on 2020-05-31 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0027_auto_20200531_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='add_ons',
        ),
        migrations.AddField(
            model_name='productincart',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('addOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.AddsOn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.ProductInCart')),
            ],
        ),
        migrations.AddField(
            model_name='addson',
            name='product_in_cart',
            field=models.ManyToManyField(through='menus.Quantity', to='menus.ProductInCart'),
        ),
    ]
