# Generated by Django 3.0.4 on 2020-05-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0030_auto_20200531_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
