# Generated by Django 3.0.4 on 2020-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0031_auto_20200531_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
