# Generated by Django 3.0.4 on 2020-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0032_quantity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
