# Generated by Django 3.0.4 on 2020-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0033_auto_20200531_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addson',
            name='product_in_cart',
        ),
        migrations.AddField(
            model_name='productincart',
            name='add_on',
            field=models.ManyToManyField(through='menus.Quantity', to='menus.AddsOn'),
        ),
    ]
