# Generated by Django 3.0.4 on 2020-06-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0034_auto_20200531_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details3.html', 'large')], default='Unique', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('Unique', 'Only'), ('x-Small', 'Extra small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('x-Large', 'Extra large'), ('Meal', 'Meal')], default='Unique', max_length=20),
        ),
    ]
