# Generated by Django 3.0.4 on 2020-06-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0035_auto_20200602_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upload_code',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='upload code'),
        ),
    ]
