# Generated by Django 3.0.4 on 2020-06-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0036_item_upload_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.CharField(blank=True, max_length=127, verbose_name='ingredients'),
        ),
    ]
