# Generated by Django 3.0.4 on 2020-06-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0037_auto_20200602_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='client',
        ),
    ]
