# Generated by Django 3.0.4 on 2020-06-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0038_remove_productincart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menus.Menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details3.html', 'large'), ('menus/details4.html', 'Xlarge')], default='Unique', max_length=20),
        ),
    ]
