# Generated by Django 3.0.4 on 2020-06-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0041_auto_20200614_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details2b.html', 'Medium B'), ('menus/details3.html', 'large'), ('menus/details4.html', 'X-large'), ('menus/details5.html', 'X-large 2'), ('menus/details6.html', 'Los_chachos'), ('menus/details7.html', 'Don_pedrito'), ('menus/details8.html', 'Margarita')], default='Unique', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('Unique', 'Only'), ('x-Small', 'Extra small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('x-Large', 'Extra large'), ('Meal', 'Meal'), ('Personal', 'Personal'), ('Mediana', 'Mediana'), ('Familiar', 'Familiar')], default='Unique', max_length=20),
        ),
    ]
