# Generated by Django 3.0.4 on 2020-07-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0042_auto_20200618_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='half',
            field=models.BooleanField(default=False),
        ),
    ]
