# Generated by Django 3.0.4 on 2020-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0043_price_half'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='address',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='city',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
