# Generated by Django 3.0.4 on 2020-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0044_auto_20200713_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='menu',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
