# Generated by Django 3.0.4 on 2020-09-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0045_auto_20200713_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.CharField(blank=True, max_length=511, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details2b.html', 'Medium B'), ('menus/details3.html', 'large'), ('menus/details4.html', 'X-large'), ('menus/details5.html', 'X-large 2'), ('menus/details6.html', 'Los_chachos'), ('menus/details7.html', 'Don_pedrito'), ('menus/details8.html', 'Margarita'), ('menus/details9.html', 'Portico'), ('menus/details10.html', 'Portico_2'), ('menus/details11.html', 'Margarita_2'), ('menus/details12.html', 'Cielo_bistro')], default='Unique', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('Unique', 'Only'), ('x-Small', 'Extra small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('x-Large', 'Extra large'), ('Meal', 'Meal'), ('Personal', 'Personal'), ('Mediana', 'Mediana'), ('Familiar', 'Familiar'), ('Shot', 'Shot'), ('Shot', 'Media'), ('50cm', '50cm'), ('30cm', '30cm')], default='Unique', max_length=20),
        ),
    ]
