# Generated by Django 3.0.4 on 2020-09-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0046_auto_20200905_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details2b.html', 'Medium B'), ('menus/details3.html', 'large'), ('menus/details4.html', 'X-large'), ('menus/details5.html', 'X-large 2'), ('menus/details6.html', 'Los_chachos'), ('menus/details7.html', 'Don_pedrito'), ('menus/details8.html', 'Margarita'), ('menus/details9.html', 'Portico'), ('menus/details10.html', 'Portico_2'), ('menus/details11.html', 'Margarita_2'), ('menus/details12.html', 'Cielo_bistro'), ('menus/portoAlto1.html', 'Porto 1'), ('menus/portoAlto2.html', 'Porto 2')], default='Unique', max_length=30),
        ),
    ]
