# Generated by Django 3.0.4 on 2020-09-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0048_auto_20200905_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['item']},
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.CharField(blank=True, max_length=511, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details2b.html', 'Medium B'), ('menus/details3.html', 'large'), ('menus/details4.html', 'X-large'), ('menus/details5.html', 'X-large 2'), ('menus/losChachos.html', 'Los_chachos'), ('menus/details7.html', 'Don_pedrito'), ('menus/details8.html', 'Margarita'), ('menus/details9.html', 'Portico'), ('menus/details10.html', 'Portico_2'), ('menus/details11.html', 'Margarita_2'), ('menus/details12.html', 'Cielo_bistro'), ('menus/portoAlto1.html', 'Porto 1'), ('menus/portoAlto2.html', 'Porto 2')], default='Unique', max_length=30),
        ),
        migrations.CreateModel(
            name='MenuAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.PositiveIntegerField(verbose_name='visits')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='menus.Menu', verbose_name='menu')),
            ],
        ),
    ]
