# Generated by Django 3.0.4 on 2020-09-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0050_auto_20200920_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuanalytic',
            name='visit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='visits'),
        ),
    ]
