# Generated by Django 3.0.4 on 2020-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0051_auto_20200920_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuanalytic',
            name='visit',
            field=models.PositiveIntegerField(default=0, verbose_name='visits'),
        ),
    ]
