# Generated by Django 3.0.4 on 2020-09-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0052_auto_20200920_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='images/default/no_photo.png', upload_to='', verbose_name='photo')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds', to='menus.Menu', verbose_name='menu')),
            ],
        ),
    ]
