# Generated by Django 3.0.4 on 2020-09-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0053_menuadvertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuadvertising',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='menus.Menu', verbose_name='menu'),
        ),
    ]
