# Generated by Django 3.0.4 on 2020-09-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0054_auto_20200921_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuadvertising',
            name='description',
            field=models.CharField(max_length=60, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='menuadvertising',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.CharField(choices=[('menus/details.html', 'Small'), ('menus/details2.html', 'Medium'), ('menus/details2b.html', 'Medium B'), ('menus/details3.html', 'large'), ('menus/details4.html', 'X-large'), ('menus/details5.html', 'X-large 2'), ('menus/losChachos.html', 'Los Chachos'), ('menus/details7.html', 'Don_pedrito'), ('menus/details8.html', 'Margarita'), ('menus/details9.html', 'Portico OLD'), ('menus/portico.html', 'Portico'), ('menus/margarita.html', 'Pizza Margarita'), ('menus/cieloBistro.html', 'Cielo Bistro'), ('menus/portoAlto1.html', 'Porto 1'), ('menus/portoAlto2.html', 'Porto 2')], default='Unique', max_length=30),
        ),
    ]
