# Generated by Django 3.0.4 on 2020-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0055_auto_20200922_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuadvertising',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='menuadvertising',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(choices=[('Unique', 'Only'), ('x-Small', 'Extra small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('x-Large', 'Extra large'), ('Meal', 'Meal'), ('Personal', 'Personal'), ('Mediana', 'Mediana'), ('Familiar', 'Familiar'), ('Shot', 'Shot'), ('Media', 'Media'), ('Botella', 'Botella'), ('50cm', '50cm'), ('30cm', '30cm')], default='Unique', max_length=20),
        ),
    ]
