# Generated by Django 3.0.4 on 2020-03-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200323_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False, verbose_name='entregado'),
        ),
    ]
